@startuml
title Diagrama de Despliegue - DonaTrack

left to right direction
skinparam shadowing false

actor Donante
actor Administrador

node "Servidor Web / Aplicación" {

  component "Sistema Donatrack" as app

  database "Base de Datos" as db

  app --> db : JDBC / SQL
}

Donante --> app : HTTPS
Administrador --> app : HTTPS

@enduml