@startuml

actor Administrador
actor Donante
actor Beneficiaria


node "Servidor" {

    component "DonaTrack\n(Monolito)" as monolito

    database "BD Relacional" as db

    monolito --> db
}

Administrador --> monolito
Donante --> monolito
Beneficiaria --> monolito

@enduml