@startuml

actor Administrador
actor Donante
actor Beneficiaria


node "Servidor" {


node "Microservicio Donaciones" {

component "API Donaciones" as apiDonaciones

database "BD Donaciones" as bdDonaciones

component "Motor Asignación\n(Async)" as motor


apiDonaciones --> bdDonaciones
motor --> bdDonaciones

}


node "Microservicio Logística" {

component "API Logística" as apiLogistica

database "BD Logística" as bdLogistica

component "Dashboard\nMonitoreo GPS" as dashboard

component "Adaptador\nProveedor GPS" as gps

component "Cliente\nPlanificador Externo" as planner


dashboard --> gps

}


}


Administrador --> apiDonaciones
Donante --> apiDonaciones
Beneficiaria --> apiDonaciones

@enduml